# coding: utf-8

"""
    DeepWork Task Management API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.interruption_create import InterruptionCreate

class TestInterruptionCreate(unittest.TestCase):
    """InterruptionCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InterruptionCreate:
        """Test InterruptionCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InterruptionCreate`
        """
        model = InterruptionCreate()
        if include_optional:
            return InterruptionCreate(
                reason = ''
            )
        else:
            return InterruptionCreate(
                reason = '',
        )
        """

    def testInterruptionCreate(self):
        """Test InterruptionCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
